/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. */
package cn.zhuatech.csm.service;
import cn.zhuatech.csm.common.BusinessException; import cn.zhuatech.csm.dto.CsmDto.*; import cn.zhuatech.csm.model.*; import cn.zhuatech.csm.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class CsmService {
    private final SuccessPlanRepository orders; private final TouchpointRecordRepository reports; private final HealthSignalRepository healthSignal; private final RiskReviewRepository riskReviews; private final CurrentUserService current;
    public CsmService(SuccessPlanRepository orders,TouchpointRecordRepository reports,HealthSignalRepository healthSignal,RiskReviewRepository riskReviews,CurrentUserService current){this.orders=orders;this.reports=reports;this.healthSignal=healthSignal;this.riskReviews=riskReviews;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getCustomerPortfolioCode();List<SuccessPlan> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findByCustomerPortfolioCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<SuccessPlanView> successPlans(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){SuccessPlan order=orders.findById(id).orElseThrow(()->new BusinessException("成功计划任务不存在"));if(order.getStatus()==SuccessPlan.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成数量不能超过任务剩余数量");order.report(request.goodQty(),request.defectQty());reports.save(new TouchpointRecord(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<SuccessPlan> list){int planned=list.stream().mapToInt(SuccessPlan::getPlannedQty).sum(),done=list.stream().mapToInt(SuccessPlan::getCompletedQty).sum(),defects=list.stream().mapToInt(SuccessPlan::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("今日成功计划",String.format("%,d",planned),list.size()+" 张成功计划任务","blue"),new Metric("成功计划完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("结果合规率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项异常","warn"),new Metric("健康信号异常",healthSignal.countByStatus(HealthSignal.Status.ALARM)+"",riskReviews.countByResult(RiskReview.Result.PENDING)+" 项待风险评审","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),healthSignal.findAllByOrderByCodeAsc().stream().map(e->new HealthSignalView(e.getCode(),e.getName(),e.getCustomerPortfolio().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),riskReviews.findTop10ByOrderByIdDesc().stream().map(i->new RiskReviewView(i.getRiskReviewNo(),i.getSuccessPlan().getOrderNo(),i.getSuccessPlan().getProductName(),i.getRiskReviewType(),i.getRiskReviewQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private SuccessPlanView view(SuccessPlan o){return new SuccessPlanView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getCustomerPortfolio().getName(),o.getCustomerPortfolio().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(SuccessPlan o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
